spring:
  application:
    name: w-ai-coder-mother-backend

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/w_ai_coder_mother
    username: root
    password: 123456
  profiles:
    active: local

  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  session:
    store-type: redis
    # session: 30天过期 [后端的过期]
    timeout: 259200

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期 [前端的过期]
    session:
      cookie:
        max-age: 259200

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wjp.waicodermotherbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      # 默认最大token数
      max-tokens: 8192
      # 严格保证结构化输出有效
      strict-json-schema: true
      response-format: json_object
    # sse流式输出
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
